require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaxonomiesController do

  # This should return the minimal set of attributes required to create a valid
  # Taxonomy. As you add validations to Taxonomy, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaxonomiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all taxonomies as @taxonomies" do
      taxonomy = Taxonomy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:taxonomies).should eq([taxonomy])
    end
  end

  describe "GET show" do
    it "assigns the requested taxonomy as @taxonomy" do
      taxonomy = Taxonomy.create! valid_attributes
      get :show, {:id => taxonomy.to_param}, valid_session
      assigns(:taxonomy).should eq(taxonomy)
    end
  end

  describe "GET new" do
    it "assigns a new taxonomy as @taxonomy" do
      get :new, {}, valid_session
      assigns(:taxonomy).should be_a_new(Taxonomy)
    end
  end

  describe "GET edit" do
    it "assigns the requested taxonomy as @taxonomy" do
      taxonomy = Taxonomy.create! valid_attributes
      get :edit, {:id => taxonomy.to_param}, valid_session
      assigns(:taxonomy).should eq(taxonomy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Taxonomy" do
        expect {
          post :create, {:taxonomy => valid_attributes}, valid_session
        }.to change(Taxonomy, :count).by(1)
      end

      it "assigns a newly created taxonomy as @taxonomy" do
        post :create, {:taxonomy => valid_attributes}, valid_session
        assigns(:taxonomy).should be_a(Taxonomy)
        assigns(:taxonomy).should be_persisted
      end

      it "redirects to the created taxonomy" do
        post :create, {:taxonomy => valid_attributes}, valid_session
        response.should redirect_to(Taxonomy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved taxonomy as @taxonomy" do
        # Trigger the behavior that occurs when invalid params are submitted
        Taxonomy.any_instance.stub(:save).and_return(false)
        post :create, {:taxonomy => {}}, valid_session
        assigns(:taxonomy).should be_a_new(Taxonomy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Taxonomy.any_instance.stub(:save).and_return(false)
        post :create, {:taxonomy => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested taxonomy" do
        taxonomy = Taxonomy.create! valid_attributes
        # Assuming there are no other taxonomies in the database, this
        # specifies that the Taxonomy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Taxonomy.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => taxonomy.to_param, :taxonomy => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested taxonomy as @taxonomy" do
        taxonomy = Taxonomy.create! valid_attributes
        put :update, {:id => taxonomy.to_param, :taxonomy => valid_attributes}, valid_session
        assigns(:taxonomy).should eq(taxonomy)
      end

      it "redirects to the taxonomy" do
        taxonomy = Taxonomy.create! valid_attributes
        put :update, {:id => taxonomy.to_param, :taxonomy => valid_attributes}, valid_session
        response.should redirect_to(taxonomy)
      end
    end

    describe "with invalid params" do
      it "assigns the taxonomy as @taxonomy" do
        taxonomy = Taxonomy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Taxonomy.any_instance.stub(:save).and_return(false)
        put :update, {:id => taxonomy.to_param, :taxonomy => {}}, valid_session
        assigns(:taxonomy).should eq(taxonomy)
      end

      it "re-renders the 'edit' template" do
        taxonomy = Taxonomy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Taxonomy.any_instance.stub(:save).and_return(false)
        put :update, {:id => taxonomy.to_param, :taxonomy => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested taxonomy" do
      taxonomy = Taxonomy.create! valid_attributes
      expect {
        delete :destroy, {:id => taxonomy.to_param}, valid_session
      }.to change(Taxonomy, :count).by(-1)
    end

    it "redirects to the taxonomies list" do
      taxonomy = Taxonomy.create! valid_attributes
      delete :destroy, {:id => taxonomy.to_param}, valid_session
      response.should redirect_to(taxonomies_url)
    end
  end

end
